defaults: &defaults
  email: dev@example.com
  secret: foo123
  ESPN_API_key: 'vdhtysj45gz85qzqn9japepp'
  #makes 'ESPN_API_key' available as ENV["ESPN_API_key"]

development:
  <<: *defaults


test:
  <<: *defaults
  email: test@example.com

production:
  <<: *defaults
  email: info@example.com
  secret: 321oof