development:
  adapter: postgresql
  encoding: unicode
  database: fanatic
  pool: 5
  username: dpappas
  password:

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
